config/routes.rb
Rails.application.routes.draw do
  root('static_pages#home')
  get('/help', to: 'static_pages#help')
  get('/about', to: 'static_pages#about')
  get('/contact', to: 'static_pages#contact')
  get('/sign_up', to: 'users#new')
  post('/sign_up', to: 'users#create')
  get('/log_in', to: 'sessions#new')
  post('/log_in', to: 'sessions#create')
  delete('/log_out', to: 'sessions#destroy')
  get('/account_activate', to: 'account_activations#activate')

  resources(:users, only: [:index, :show, :edit, :update, :destroy]) do
    member do
      get(:followings, :followers)
    end
  end
  resources(:password_resets, only: [:new, :create, :edit, :update])
  resources(:microposts, only: [:create, :destroy])
  resources(:relationships, only: [:create, :destroy])
end

app/models/user.rb
class User < ApplicationRecord
  has_many(:microposts, dependent: :destroy)

  has_many(:active_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy)
  has_many(:followings, through: :active_relationships, source: :followed)
  has_many(:passive_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy)
  has_many(:followers, through: :passive_relationships, source: :follower)

  attr_accessor(:remember_token, :activation_token, :reset_token)

  VALID_EMAIL_REGEXP = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates(:name, presence: true, length: { maximum: 50} )
  validates(:email, presence: true, length: { maximum: 255},
    format: { with: VALID_EMAIL_REGEXP }, uniqueness: { case_sensitive: false } )
  validates(:password, presence: true, length: { minimum: 6 }, unless: -> { password.nil? } )

  before_save { self.email = email.downcase }
  before_create(:create_activation_digest)
  after_create { UserMailer.account_activation(self).deliver_now }

  default_scope(-> { order(id: :asc) })


  has_secure_password

  class << self
    def digest(token)
      BCrypt::Password.create(token)
    end

    def create_token
      SecureRandom.urlsafe_base64(24)
    end
  end

  def remember
    self.remember_token = self.class.create_token
    update(remember_digest: self.class.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest".to_sym)
    return false if digest.nil?
    BCrypt::Password.new(digest) == token
  end

  def forget
    update(remember_digest: nil)
  end

  def create_reset_token_and_digest
    self.reset_token = self.class.create_token
    reset_digest = self.class.digest(reset_token)
    update(reset_digest: reset_digest, reset_sent_at: Time.zone.now)
  end

  def send_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at > 1.day.ago
  end

  def feed
    microposts
  end

  def follow(other_user)
    relationship = active_relationships.new(followed_id: other_user.id)
    relationship.save
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  private
    def create_activation_digest
      self.activation_token = self.class.create_token
      self.activation_digest = self.class.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action(:logged_in_user, only: [:edit, :update, :index, :show, :destroy, :followings, :followers])
  before_action(:correct_user, only: [:edit, :update])
  before_action(:admin_user, only: [:destroy])

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      remember(@user)
      flash[:success] = 'メールをチェックしてアカウントを有効化してください'
      redirect_to(@user)
    else
      render('new')
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を更新しました'
      redirect_to(@user)
    else
      render('edit')
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'ユーザーを削除しました'
    redirect_to(users_url)
  end

  def followers
    @title = 'フォロワー'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
    render('show_follow')
  end

  def followings
    @title = 'フォローユーザー'
    @user = User.find(params[:id])
    @users = @user.followings.paginate(page: params[:page], per_page: 10)
    render('show_follow')
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def admin_user
      redirect_to(request.original_url || root_url) unless current_user.admin
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.new, local: true) do |f|%>
  <%= f.hidden_field_tag(:id, @user.id) %>
  <%= f.submit('follow', class: 'btn btn-primary') %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div class="follow-form">
    <% if current_user.following?(@user) %>
      <%= render('unfollow') %>
    <% else %>
      <%= render('follow') %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="form-group">
  <%= f.label(:email) %>
  <%= f.email_field(:email, class: 'form-control') %>
</div>

<div class="form-group">
  <%= f.label(:name) %>
  <%= f.text_field(:name, class: 'form-control') %>
</div>

<div class="form-group">
  <%= f.label(:password) %>
  <%= f.password_field(:password, class: 'form-control') %>
</div>

<div class="form-group">
  <%= f.label(:password_confirmation) %>
  <%= f.password_field(:password_confirmation, class: 'form-control') %>
</div>

<%= f.submit(yield(:button_text), class: 'btn btn-primary w-100 mt-3') %>

app/views/users/_show_follow.html.erb
<%= provide(:title, @title) %>

app/views/users/_unfollow.html.erb
<%= link_to('unfollow', relationship_path(current_user.active_relationships.find_by(followed_id: @user.id)),
  method: :delete, class: 'btn btn-danger') %>

app/views/users/_user.html.erb
<li class="border-bottom border-secondary mb-3">
  <%= gravatar_for(user) %>
  <%= link_to(user.name, user) %>
  <%= link_to('削除', user, method: :delete, class: 'btn btn-danger')%>
<li>

app/views/users/edit.html.erb
<%= provide(:title, 'ユーザー情報編集') %>
<%= provide(:button_text, '更新') %>
<h1 class="text-center">ユーザー情報編集</h1>

<div class="row d-flex justify-content-center">
  <div class="col-md-6">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render('shared/error_messages', object: @user) %>

      <%= render(partial: 'form', locals: { f: f }) %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'ユーザー一覧') %>
<h1 class="text-center">ユーザー一覧</h1>

<div>
  <ul class="list-unstyled">
    <%= render(@users) %>
  </ul>

  <div class="d-flex justify-content-center">
    <%= will_paginate(@users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer) %>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title, '新規登録') %>
<%= provide(:button_text, '登録') %>
<h1 class="text-center">新規登録</h1>

<div class="row d-flex justify-content-center">
  <div class="col-md-6">
    <%= form_with(model: @user, url: sign_up_path, local: true) do |f| %>
      <%= render('shared/error_messages', object: @user) %>

      <%= render(partial: 'form', locals: { f: f }) %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-4">
    <%= gravatar_for(@user) %>
    <h1><%= @user.name %></h1>
    <%= render('follow_form') %>
  </div>
  <div class="col-md-8">
    <% unless @microposts.empty? %>
      <h2>マイクロポスト（<%= @user.microposts.count %>）</h2>
      <%= render(@microposts) %>
      <%= will_paginate(@microposts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer) %>
    <% end %>
  </div>
</div>