config/routes.rb
Rails.application.routes.draw do
  root('static_pages#home')
  get('/help', to: 'static_pages#help')
  get('/about', to: 'static_pages#about')
  get('/contact', to: 'static_pages#contact')
  get('/sign_up', to: 'users#new')
  post('/sign_up', to: 'users#create')
  get('/log_in', to: 'sessions#new')
  post('/log_in', to: 'sessions#create')
  delete('/log_out', to: 'sessions#destroy')
  get('/account_activate', to: 'account_activations#activate')

  resources(:users, only: [:index, :show, :edit, :update, :destroy]) do
    member do
      get(:followings, :followers)
    end
  end
  resources(:password_resets, only: [:new, :create, :edit, :update])
  resources(:microposts, only: [:create, :destroy])
  resources(:relationships, only: [:create, :destroy])
end

app/views/shared/_error_messages.html.erb
<% unless object.errors.full_messages.empty? %>
  <div class="alert alert-danger">
    <%= "#{object.errors.count}個のエラーがあります。" %>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<%= render(@feed_items) %>

<%= will_paginate(@feed_items, renderer: WillPaginate::ActionView::BootstrapLinkRenderer) %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render('shared/error_messages', object: @micropost) %>

  <%= f.text_area(:content, placeholder: '140字以内', class: 'form-control mb-2') %>
  <%= f.file_field(:image) %>
  <%= f.submit('投稿', class: 'btn btn-primary w-100') %>
<% end %>

app/views/shared/_status.html.erb
<% @user ||= current_user %>
<div class="d-flex">
  <div class="followers-count">
    <%= link_to("#{@user.followings.count} folowers", followings_user_path(@user)) %>
  </div>
  <div class="followings-count">
    <%= link_to("#{@user.followings.count} followings", followers_user_path(@user)) %>
  </div>
</div>

app/views/shared/_user_info.html.erb
<div class="d-flex">
  <div class="mr-3"><%= gravatar_for(current_user) %></div>

  <div>
    <h3 class="mb-0"><%= current_user.name %></h3>
    <%= link_to('プロフィール', current_user, class: 'd-block') %>
    <p class="d-block"><%= current_user.microposts.count %>投稿</p>
  </div>
</div>