config/routes.rb
Rails.application.routes.draw do
  root('static_pages#home')
  get('/help', to: 'static_pages#help')
  get('/about', to: 'static_pages#about')
  get('/contact', to: 'static_pages#contact')
  get('/sign_up', to: 'users#new')
  post('/sign_up', to: 'users#create')
  get('/log_in', to: 'sessions#new')
  post('/log_in', to: 'sessions#create')
  delete('/log_out', to: 'sessions#destroy')
  get('/account_activate', to: 'account_activations#activate')

  resources(:users, only: [:index, :show, :edit, :update, :destroy]) do
    member do
      get(:followings, :followers)
    end
  end
  resources(:password_resets, only: [:new, :create, :edit, :update])
  resources(:microposts, only: [:create, :destroy])
  resources(:relationships, only: [:create, :destroy])
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-5">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav class="border-top border-secondary">
    <ul class="d-flex justify-content-end list-unstyled">
      <li><%= link_to "About", about_path %></li>
      <li class="pl-1"><%= link_to "Contact", contact_path %></li>
      <li class="pl-1"><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg">
  <div class="container">
    <%= link_to('Sample App', root_path, id: 'logo', class: 'navbar-bland') %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item"><%= link_to('ホーム', root_path , class: 'nav-link') %></li>
        <li class="nav-item"><%= link_to('ヘルプ', help_path, class: 'nav-link') %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to('ユーザー一覧', users_path, class: 'nav-link') %></li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">アカウント</a>

            <ul class="dropdown-menu">
              <li class="nav-item"><%= link_to('プロフィール', current_user, class: 'nav-link') %></li>
              <li class="nav-item"><%= link_to('ログアウト', log_out_path, method: :delete, class: 'nav-link') %></li>
            </ul>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to('ログイン', log_in_path, class: 'nav-link') %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render('layouts/header') %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render('layouts/footer') %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>